"""Refresh the auto-generated frame-strip blocks in `README.md`.

For each tape file in `tools/demo/*.tape`, finds the matching PNG
snapshots in `docs/frames/<slug>-<n>-<label>.png`, generates a
markdown table of clickable thumbnails, and writes it between the
matching marker comments in `README.md`. Markers look like:

    <!-- BEGIN demo-frames: <slug> -->
    ...auto-generated content...
    <!-- END demo-frames: <slug> -->

Invoked from the Makefile after `make demos` so the embedded scene
strips always reflect what the tapes produced. Adding a scene to a
tape (or removing one) automatically reflows the strip on the next
render — no manual markdown edit required.

Usage:

    uv run python tools/demo/refresh_readme_frames.py          # rewrite if stale
    uv run python tools/demo/refresh_readme_frames.py --check  # exit 1 if stale

Loud failure modes:

- Markers for an existing tape are absent from README.md.
- Markers are mis-paired (BEGIN without END or vice versa).
- A tape exists but has no rendered PNG frames yet — silent skip
  (this is normal before the first `make demos`).

Pattern documented in issue #40.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
README_PATH = REPO_ROOT / "README.md"
FRAMES_DIR = REPO_ROOT / "docs" / "frames"
TAPES_DIR = REPO_ROOT / "tools" / "demo"

# `<slug>-<n>-<label>.png`. The non-greedy slug means `discover-datasets-1-list`
# correctly parses as slug=`discover-datasets`, n=1, label=`list` (rather than
# slug=`discover` with a leftover `datasets` chunk).
FRAME_RE = re.compile(r"^(?P<slug>.+?)-(?P<n>\d+)-(?P<label>.+)\.png$")

THUMBNAIL_WIDTH = 200


def collect_frames(slug: str) -> list[tuple[int, str, Path]]:
    """Return `[(n, label, path)]` for `<slug>-<n>-<label>.png`, sorted by n.

    Files that don't match the `<slug>-<n>-<label>.png` shape are
    silently skipped. Files whose slug doesn't equal `slug` exactly
    are also skipped — that's how we keep slug `demo` from matching
    `discover-datasets-*.png` (the non-greedy regex would otherwise
    parse the latter with slug=`discover-datasets`, which doesn't
    equal `demo`, so we drop it).
    """
    frames: list[tuple[int, str, Path]] = []
    for path in sorted(FRAMES_DIR.glob(f"{slug}-*.png")):
        m = FRAME_RE.match(path.name)
        if not m or m.group("slug") != slug:
            continue
        frames.append((int(m.group("n")), m.group("label"), path))
    frames.sort()
    return frames


def render_strip_md(frames: list[tuple[int, str, Path]]) -> str:
    """Generate the markdown table for one tape's scene-strip.

    Header row uses `<n>. <Pretty Label>`, body row links each thumbnail
    image to the full-resolution PNG. The link wrapping is what gives
    us GitHub's built-in lightbox on click (no JS, no CSS).
    """
    headers: list[str] = []
    cells: list[str] = []
    for n, label, path in frames:
        pretty = label.replace("-", " ").replace("_", " ").title()
        headers.append(f"{n}. {pretty}")
        rel = path.relative_to(REPO_ROOT).as_posix()
        cells.append(f'[<img src="{rel}" width="{THUMBNAIL_WIDTH}">]({rel})')
    aligns = [":-:"] * len(frames)
    return (
        "| " + " | ".join(headers) + " |\n"
        "| " + " | ".join(aligns) + " |\n"
        "| " + " | ".join(cells) + " |"
    )


def begin_marker(slug: str) -> str:
    return f"<!-- BEGIN demo-frames: {slug} -->"


def end_marker(slug: str) -> str:
    return f"<!-- END demo-frames: {slug} -->"


def replace_block(text: str, slug: str, strip_md: str) -> str:
    """Return `text` with the slug's BEGIN/END block replaced.

    Raises `RuntimeError` loudly if the markers are missing or
    unmatched — we never silently skip an expected slug.
    """
    begin = begin_marker(slug)
    end = end_marker(slug)

    begin_count = text.count(begin)
    end_count = text.count(end)
    if begin_count != end_count:
        raise RuntimeError(
            f"Unmatched markers for slug {slug!r} in README.md: "
            f"{begin_count} BEGIN vs {end_count} END."
        )
    if begin_count == 0:
        raise RuntimeError(
            f"Markers for slug {slug!r} not found in README.md.\n"
            f"Add a marker pair like:\n\n"
            f"    {begin}\n"
            f"    (auto-generated content goes here)\n"
            f"    {end}\n"
        )

    pattern = re.compile(
        re.escape(begin) + r".*?" + re.escape(end),
        re.DOTALL,
    )
    replacement = (
        f"{begin}\n"
        f"<!-- generated by `make demos`; do not edit by hand -->\n"
        f"{strip_md}\n"
        f"{end}"
    )
    return pattern.sub(replacement, text, count=1)


def tape_slugs() -> list[str]:
    """All slugs from `tools/demo/*.tape`, sorted."""
    return sorted(p.stem for p in TAPES_DIR.glob("*.tape"))


def run(check: bool) -> int:
    slugs = tape_slugs()
    if not slugs:
        print("No tapes found in tools/demo/", file=sys.stderr)
        return 1

    original = README_PATH.read_text(encoding="utf-8")
    updated = original

    skipped: list[str] = []
    rewritten: list[str] = []

    for slug in slugs:
        frames = collect_frames(slug)
        if not frames:
            skipped.append(slug)
            continue
        strip_md = render_strip_md(frames)
        new_text = replace_block(updated, slug, strip_md)
        if new_text != updated:
            rewritten.append(slug)
        updated = new_text

    if check:
        if updated != original:
            print(
                "README.md frame strips are stale relative to docs/frames/. "
                "Run `make demos` (or `python tools/demo/refresh_readme_frames.py`) "
                "and commit the result.",
                file=sys.stderr,
            )
            return 1
        print(f"README.md frame strips in sync ({len(slugs)} tape(s) checked).")
        return 0

    if updated != original:
        README_PATH.write_text(updated, encoding="utf-8")
        print(
            f"README.md frame strips refreshed: {', '.join(rewritten) or '(none)'}"
        )
    else:
        print("README.md frame strips already in sync.")
    if skipped:
        print(
            f"  Skipped (no PNGs rendered yet): {', '.join(skipped)}",
            file=sys.stderr,
        )
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check",
        action="store_true",
        help=(
            "Don't write README.md; exit 1 if the generated content would "
            "differ from the committed README. Use in CI to catch drift."
        ),
    )
    args = parser.parse_args()
    return run(check=args.check)


if __name__ == "__main__":
    sys.exit(main())
