"""Generate the static SA2 5-digit → 9-digit mapping bundled with the DSS parser.

ABS publishes the Edition 2 SA2 boundary file with both ``SA2_MAIN16`` (9-digit
canonical code) and ``SA2_5DIG16`` (5-digit short code) columns. Pre-Q2-2023
DSS releases use the 5-digit form in their XLSX files; later releases switched
to 9-digit. The DSS parser ``census_augment.datasets._dss._parse_xlsx``
converts 5-digit codes to 9-digit at parse time via the bundled static dict
generated by this tool.

Why bundle vs runtime-derive: ABS Edition 2 codes are **frozen** — they were
finalised when Edition 2 ASGS shipped (2016) and don't change. A static lookup
keeps the DSS parser dependency-free (no boundary fetch needed mid-parse) and
makes the conversion deterministic.

Run with::

    uv run python tools/generate_dss_sa2_5to9.py

Writes to ``src/census_augment/datasets/_dss_sa2_5digit_edition_2.py`` — a
~63 KB Python module containing one ``dict[str, str]`` constant. Re-running
is idempotent for a fixed Edition 2 ABS release.

Real Data First: the input is the live ABS Edition 2 SA2 shapefile, fetched
via :class:`BoundariesDataSource` exactly as the runtime would. No synthesis.

See ``CLAUDE.md`` "Real Data First" + issue #99.
"""

from __future__ import annotations

import sys
from pathlib import Path

try:
    from census_augment.config import DEFAULT_BOUNDARIES_URL, CensusConfig
    from census_augment.data_sources.boundaries import BoundariesDataSource
    from census_augment.paths import default_data_dir
except ModuleNotFoundError as e:
    sys.stderr.write(
        "ERROR: census_augment is not importable from the active Python "
        f"({sys.executable}).\n\n"
        f"Underlying error: {e}\n\n"
        "Run with `uv run python tools/generate_dss_sa2_5to9.py` instead.\n"
    )
    sys.exit(2)


OUTPUT_PATH = (
    Path(__file__).resolve().parent.parent
    / "src"
    / "census_augment"
    / "datasets"
    / "_dss_sa2_5digit_edition_2.py"
)


def main() -> int:
    data_dir = default_data_dir()
    print(f"Cache root: {data_dir}")
    print("Fetching ABS Edition 2 SA2 boundary (~50 MB, cached after first run)...")

    e2 = BoundariesDataSource(
        census=CensusConfig(year=2016, asgs_edition=2, datum="GDA94"),
        base_url=DEFAULT_BOUNDARIES_URL,
        root=data_dir / "boundaries" / "2016",
    )
    gdf = e2.load()
    print(f"Loaded boundary: {len(gdf)} SA2s")

    if "SA2_5DIG16" not in gdf.columns or "SA2_MAIN16" not in gdf.columns:
        print(
            "ERROR: boundary GDF is missing the expected columns "
            "(SA2_5DIG16 / SA2_MAIN16). Got: "
            f"{list(gdf.columns)}",
            file=sys.stderr,
        )
        return 1

    mapping: dict[str, str] = {}
    collisions: list[tuple[str, str, str]] = []
    for code5_raw, code9_raw in zip(gdf["SA2_5DIG16"], gdf["SA2_MAIN16"], strict=False):
        code5 = str(code5_raw)
        code9 = str(code9_raw)
        if code5 in mapping and mapping[code5] != code9:
            collisions.append((code5, mapping[code5], code9))
        mapping[code5] = code9

    if collisions:
        print(
            f"ERROR: found {len(collisions)} collisions in the 5→9 mapping.",
            file=sys.stderr,
        )
        for c in collisions[:5]:
            print(f"  5-digit {c[0]} maps to BOTH {c[1]} and {c[2]}", file=sys.stderr)
        return 1

    print(f"Unique 5-digit codes: {len(mapping)} (no collisions)")

    # Write a deterministic Python source file. Sort keys so repeat runs
    # produce identical output (helpful for diffing / version control).
    lines: list[str] = []
    lines.append('"""Static SA2 5-digit → 9-digit code mapping for ASGS Edition 2.')
    lines.append("")
    lines.append("Auto-generated by ``tools/generate_dss_sa2_5to9.py``. Do not hand-edit;")
    lines.append("re-run the tool to regenerate.")
    lines.append("")
    lines.append("Used by ``DssDataSource._parse_xlsx`` to convert older DSS releases")
    lines.append("(pre-Q2-2023) that use 5-digit ``SA2_5DIG16`` codes in their XLSX")
    lines.append("files to the 9-digit ``SA2_MAIN16`` form the rest of the augmentor")
    lines.append("uses. ABS Edition 2 codes are frozen so this mapping never goes")
    lines.append("stale.")
    lines.append('"""')
    lines.append("")
    lines.append("SA2_5DIG_TO_MAIN_EDITION_2: dict[str, str] = {")
    for code5 in sorted(mapping):
        lines.append(f"    {code5!r}: {mapping[code5]!r},")
    lines.append("}")

    OUTPUT_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    size = OUTPUT_PATH.stat().st_size
    print(f"Wrote {OUTPUT_PATH} ({size:,} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
